<!-- Q2. Write a python script to
Construct two numpy 3D arrays A1 and A2 of any shape set by the user at run time and the elements are randomly generated by the system. Perform the following steps
1) Construct an array by selecting all the elements of the first array (A1) that are divisible by 5
2) Construct another array by selecting all the elements of the second array (A2) that are divisible by 4
3) Join 1 and 2 to form a single dimensional array and construct the largest possible square matrix from it -->


<!-- . Write a python script to
Construct two numpy 3D arrays A1 and A2 of any shape set by the user at run time and the elements are randomly generated by the system. Perform the following steps
1) Construct an array by selecting all the elements of the first array (A1) that are divisible by 5
2) Construct another array by selecting all the elements of the second array (A2) that are divisible by 4
3) Join 1 and 2 to form a single dimensional array and construct the largest possible square matrix from it -->


<!-- Q2. Write a python script to
Construct two numpy 3D arrays A1 and A2 of any shape set by the user at run time and the elements are randomly generated by the system. Perform the following steps
1) Construct an array by selecting all the elements of the first array (A1) that are divisible by 5
2) Construct another array by selecting all the elements of the second array (A2) that are divisible by 4
3) Join 1 and 2 to form a single dimensional array and construct the largest possible square matrix from it -->


In [1]:
import numpy as np

# Step 1: Create two 3D arrays with random elements
def create_random_3d_array(shape):
    """Generate a 3D numpy array with random integers between 1 and 100."""
    return np.random.randint(1, 101, size=shape)

# Get shape from the user
shape1 = tuple(map(int, input("Enter the shape of the first 3D array (e.g., 2 3 4): ").split()))
shape2 = tuple(map(int, input("Enter the shape of the second 3D array (e.g., 3 2 3): ").split()))

# Generate arrays
A1 = create_random_3d_array(shape1)
A2 = create_random_3d_array(shape2)

print("\nFirst Array (A1):\n", A1)
print("\nSecond Array (A2):\n", A2)

# Step 2: Select elements divisible by 5 in A1
A1_div_5 = A1[A1 % 5 == 0]
print("\nElements of A1 divisible by 5:\n", A1_div_5)

# Step 3: Select elements divisible by 4 in A2
A2_div_4 = A2[A2 % 4 == 0]
print("\nElements of A2 divisible by 4:\n", A2_div_4)

# Step 4: Combine both arrays into a single-dimensional array
combined_array = np.concatenate((A1_div_5, A2_div_4))
print("\nCombined 1D Array:\n", combined_array)

# Step 5: Construct the largest possible square matrix
length = len(combined_array)
side_length = int(np.sqrt(length))  # Largest possible square side
square_matrix = combined_array[:side_length**2].reshape(side_length, side_length)
print("\nLargest Possible Square Matrix:\n", square_matrix)



First Array (A1):
 [[[ 41 100  70  29]
  [ 34  23  45  74]
  [ 21  77  98  64]]

 [[ 32  36   6   9]
  [ 78   5  60   4]
  [ 57  61  30  67]]]

Second Array (A2):
 [[[ 56  38  43]
  [  8  10  50]]

 [[ 50   4   1]
  [ 66  90 100]]

 [[ 85  84  12]
  [ 11  42  34]]]

Elements of A1 divisible by 5:
 [100  70  45   5  60  30]

Elements of A2 divisible by 4:
 [ 56   8   4 100  84  12]

Combined 1D Array:
 [100  70  45   5  60  30  56   8   4 100  84  12]

Largest Possible Square Matrix:
 [[100  70  45]
 [  5  60  30]
 [ 56   8   4]]
