<!-- Q3. Define a function Create_Array () that can create an array of flexible size according to the number of arguments passed within the function call. The elements passed in the function should make the diagonal Elements of the array and the rest of the elements can be all zeros
For Example, if the function call is Create_Array(1,2,3,4)
The function shall return
1 0 0 0
0 2 0 0
0 0 3 0
0 0 0 4 -->


<!-- Q3. Define a function Create_Array () that can create an array of flexible size according to the number of arguments passed within the function call. The elements passed in the function should make the diagonal Elements of the array and the rest of the elements can be all zeros
For Example, if the function call is Create_Array(1,2,3,4)
The function shall return
1 0 0 0
0 2 0 0
0 0 3 0
0 0 0 4 -->


 <!-- Define a function Create_Array () that can create an array of flexible size according to the number of arguments passed within the function call. The elements passed in the function should make the diagonal Elements of the array and the rest of the elements can be all zeros
For Example, if the function call is Create_Array(1,2,3,4)
The function shall return
1 0 0 0
0 2 0 0
0 0 3 0
0 0 0 4 -->


In [1]:
import numpy as np

def Create_Array(*args):
    """
    Create a square array where the diagonal elements are the arguments passed,
    and the rest of the elements are zeros.
    """
    n = len(args)  # Determine the size of the array
    array = np.zeros((n, n), dtype=int)  # Create an n x n array filled with zeros
    np.fill_diagonal(array, args)  # Fill the diagonal with the arguments
    return array

# Example usage
result = Create_Array(1, 2, 3, 4)
print("Resultant Array:")
print(result)


Resultant Array:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
